### ISSUE TITLE
Too few Tom's in your life

### ISSUE THREAD

**Issue by tomandersson** [benfoxall/benfoxall.github.com#42]
- [x] Invite
- [x] Tom
- [x] to
- [x] come
- [x] visit

**Comment by tomandersson** [comment]
Also, happy birthday I guess ..?

**Comment by benfoxall** [comment]
I've updated your issue to make the key points into check boxes; then I've checked them all, because…

# Tom, would you please come and visit me sometime?  (I would like that very much)

Would May work?  I'd be good for the 1st, 2nd, or 4th weekends.  Or, any time in June.  Or any other time I guess.

I look forward to being an awesome host.

(also, THANK YOU - I guess)

**Comment by benfoxall** [comment]
@dubussi has some issues with this issue

**Comment by dubaussi** [comment]
I'm not happy with the way this issue has been written. I think we are approaching this in a too linear fashion. I'd like to break it down into a series of smaller tasks/logic statements and then prioritise these

e.g.

Would Tom like to visit?
Would Tom like to visit Ben?
Would Tom like to visit Ben (with the following conditions):
   Location: Oxford/Elsewhere
   Specific location: Ben's flat/public venue
   
Time: Day/Month/Year

We also need to specify length of stay.

Going by the original acceptance criteria, we also need to clarify the range of Tom's that Ben needs in his life.

Lots of work still to be done on this. I can set up a strategy workshop if this helps?

**Comment by tomandersson** [comment]
Not "Fixed" :(
